/**
 * Browser (IANA) time zone -> the Windows name Microsoft Bookings expects.
 * Bookings uses it to word the visitor's confirmation email in their own time.
 * Covers the zones AMIPI's customers realistically book from; anything else
 * falls back to AMIPI's own zone, which is still a correct time, just not a
 * localised one.
 */
const MAP: Record<string, string> = {
  "Pacific/Honolulu": "Hawaiian Standard Time",
  "America/Anchorage": "Alaskan Standard Time",
  "America/Los_Angeles": "Pacific Standard Time",
  "America/Vancouver": "Pacific Standard Time",
  "America/Tijuana": "Pacific Standard Time (Mexico)",
  "America/Phoenix": "US Mountain Standard Time",
  "America/Denver": "Mountain Standard Time",
  "America/Edmonton": "Mountain Standard Time",
  "America/Chicago": "Central Standard Time",
  "America/Winnipeg": "Central Standard Time",
  "America/Mexico_City": "Central Standard Time (Mexico)",
  "America/Regina": "Canada Central Standard Time",
  "America/Guatemala": "Central America Standard Time",
  "America/Costa_Rica": "Central America Standard Time",
  "America/New_York": "Eastern Standard Time",
  "America/Detroit": "Eastern Standard Time",
  "America/Toronto": "Eastern Standard Time",
  "America/Indiana/Indianapolis": "US Eastern Standard Time",
  "America/Panama": "SA Pacific Standard Time",
  "America/Bogota": "SA Pacific Standard Time",
  "America/Lima": "SA Pacific Standard Time",
  "America/Jamaica": "SA Pacific Standard Time",
  "America/Halifax": "Atlantic Standard Time",
  "America/Puerto_Rico": "SA Western Standard Time",
  "America/Santo_Domingo": "SA Western Standard Time",
  "America/Caracas": "Venezuela Standard Time",
  "America/Santiago": "Pacific SA Standard Time",
  "America/St_Johns": "Newfoundland Standard Time",
  "America/Sao_Paulo": "E. South America Standard Time",
  "America/Argentina/Buenos_Aires": "Argentina Standard Time",
  "America/Montevideo": "Montevideo Standard Time",
  "Atlantic/Azores": "Azores Standard Time",
  "Atlantic/Reykjavik": "Greenwich Standard Time",
  UTC: "UTC",
  "Etc/UTC": "UTC",
  "Europe/London": "GMT Standard Time",
  "Europe/Dublin": "GMT Standard Time",
  "Europe/Lisbon": "GMT Standard Time",
  "Africa/Casablanca": "Morocco Standard Time",
  "Europe/Paris": "Romance Standard Time",
  "Europe/Brussels": "Romance Standard Time",
  "Europe/Madrid": "Romance Standard Time",
  "Europe/Copenhagen": "Romance Standard Time",
  "Europe/Berlin": "W. Europe Standard Time",
  "Europe/Amsterdam": "W. Europe Standard Time",
  "Europe/Rome": "W. Europe Standard Time",
  "Europe/Zurich": "W. Europe Standard Time",
  "Europe/Vienna": "W. Europe Standard Time",
  "Europe/Stockholm": "W. Europe Standard Time",
  "Europe/Oslo": "W. Europe Standard Time",
  "Europe/Luxembourg": "W. Europe Standard Time",
  "Europe/Prague": "Central Europe Standard Time",
  "Europe/Budapest": "Central Europe Standard Time",
  "Europe/Belgrade": "Central Europe Standard Time",
  "Europe/Warsaw": "Central European Standard Time",
  "Africa/Lagos": "W. Central Africa Standard Time",
  "Europe/Athens": "GTB Standard Time",
  "Europe/Bucharest": "GTB Standard Time",
  "Europe/Helsinki": "FLE Standard Time",
  "Europe/Kyiv": "FLE Standard Time",
  "Europe/Kiev": "FLE Standard Time",
  "Europe/Sofia": "FLE Standard Time",
  "Africa/Cairo": "Egypt Standard Time",
  "Africa/Johannesburg": "South Africa Standard Time",
  "Africa/Gaborone": "South Africa Standard Time",
  "Asia/Jerusalem": "Israel Standard Time",
  "Asia/Beirut": "Middle East Standard Time",
  "Europe/Istanbul": "Turkey Standard Time",
  "Europe/Moscow": "Russian Standard Time",
  "Asia/Riyadh": "Arab Standard Time",
  "Asia/Kuwait": "Arab Standard Time",
  "Asia/Qatar": "Arab Standard Time",
  "Asia/Bahrain": "Arab Standard Time",
  "Africa/Nairobi": "E. Africa Standard Time",
  "Asia/Tehran": "Iran Standard Time",
  "Asia/Dubai": "Arabian Standard Time",
  "Asia/Muscat": "Arabian Standard Time",
  "Asia/Karachi": "Pakistan Standard Time",
  "Asia/Kolkata": "India Standard Time",
  "Asia/Calcutta": "India Standard Time",
  "Asia/Colombo": "Sri Lanka Standard Time",
  "Asia/Kathmandu": "Nepal Standard Time",
  "Asia/Dhaka": "Bangladesh Standard Time",
  "Asia/Bangkok": "SE Asia Standard Time",
  "Asia/Jakarta": "SE Asia Standard Time",
  "Asia/Ho_Chi_Minh": "SE Asia Standard Time",
  "Asia/Saigon": "SE Asia Standard Time",
  "Asia/Shanghai": "China Standard Time",
  "Asia/Hong_Kong": "China Standard Time",
  "Asia/Macau": "China Standard Time",
  "Asia/Singapore": "Singapore Standard Time",
  "Asia/Kuala_Lumpur": "Singapore Standard Time",
  "Asia/Manila": "Singapore Standard Time",
  "Asia/Taipei": "Taipei Standard Time",
  "Australia/Perth": "W. Australia Standard Time",
  "Asia/Tokyo": "Tokyo Standard Time",
  "Asia/Seoul": "Korea Standard Time",
  "Australia/Darwin": "AUS Central Standard Time",
  "Australia/Adelaide": "Cen. Australia Standard Time",
  "Australia/Brisbane": "E. Australia Standard Time",
  "Australia/Sydney": "AUS Eastern Standard Time",
  "Australia/Melbourne": "AUS Eastern Standard Time",
  "Australia/Hobart": "Tasmania Standard Time",
  "Pacific/Auckland": "New Zealand Standard Time",
  "Pacific/Fiji": "Fiji Standard Time",
};

/** AMIPI's office (New York). */
export const BUSINESS_TIME_ZONE = "Eastern Standard Time";

export const toWindowsTimeZone = (iana: string) => MAP[iana] ?? BUSINESS_TIME_ZONE;
